In [14]:
a = [[1,2,3],[1,4,5]]


In [15]:
import numpy as np
scores = np.array(a)

In [16]:
shift_scores = scores - np.max(scores, axis=1)[..., np.newaxis]

In [17]:
shift_scores

array([[-2, -1,  0],
       [-4, -1,  0]])

In [18]:
softmax_scores = np.exp(shift_scores) / np.sum(np.exp(shift_scores), axis=1)[..., np.newaxis]

In [19]:
softmax_scores

array([[0.09003057, 0.24472847, 0.66524096],
       [0.01321289, 0.26538793, 0.72139918]])

In [20]:
y = np.array([[1],[2]])

In [21]:
correct_class_scores = np.choose(y, shift_scores.T)

In [22]:
correct_class_scores

array([[-1, -1],
       [ 0,  0]])

In [26]:
y = np.array([1,0])

In [27]:
a = np.choose(y,shift_scores.T)

In [28]:
a

array([-1, -4])